meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::. #tiles/S_term_single2

# Basics
DESIGN_NAME: S_term_single2
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 205, 56.25]
pdk::gf180mcuD:
    # Width should be multiple of 0.56 (Metal2 pitch)
    # Height should be multiple of 0.56 (Metal3 pitch)
    # Standard cell row height: 3.92 (8 Metal3 track)
    DIE_AREA: [0, 0, 316.40, 71.12]
    BOTTOM_MARGIN_MULT: 1
    TOP_MARGIN_MULT: 1

SYNTH_LATCH_MAP: dir::../../latch_map.v
